title ler inv e print matriz
.model small

.stack 100h

.data 

    n equ 3
    matriz db n dup(n dup(?))

.code 
 MAIN PROC
MOV AX,@DATA ; INICIALIZO DS
MOV DS,AX

LEA BX,MATRIZ

MOV CH,n ; #LINHAS
MOV DH,n ; #COLUNAS

CALL LER ; LEITURA DA MATRIZ

LEA BX,MATRIZ
MOV CH,3 ; #LINHAS
MOV DH,3 ; #COLUNAS

CALL IMPRIME ; IMPRIME MATRIZ LIDA
LEA BX,MATRIZ
MOV CH,3 ; #LINHAS
MOV DH,3 ; #COLUNAS

CALL inv ; ZERA ELEMENTOS DA MATRIZ


MAIN ENDP
LER PROC NEAR
; LE UMA MATRIZ M X N E ARMAZENA NA MEMORIA
; ENTRADA - BX O OFFSET DA MATRIZ, CH NUMERO DE LINHAS E DH NUMERO DE COLUNAS
; SAIDA - MATRIZ ARMAZENADA NA MEMORIA
PUSH AX
PUSH BX
PUSH CX
PUSH DX
PUSH SI
; MOV CH,3 ; # LINHAS
; XOR BX,BX ; INDICE COLUNA
MOV AH,1
COLUNA_LE: ; IMPRIEM UMA COLUNA
MOV CL,DH ; # COLUNAS
XOR SI,SI ; INDICE LINHA
LINHA_LE: ; IMPIRME UMA LINHA
INT 21H ; LE O ELEMENTO EM CARACTER
AND AL,0FH ; CARACTER -> NUMERO
MOV [BX][SI],AL
INC SI ; PROXIMA COLUNA
DEC CL
JNZ LINHA_LE
ADD BX,3 ; PROXIMA LINHA
DEC CH
JNZ COLUNA_LE
POP SI
POP DX
POP CX
POP BX
POP AX
RET
LER ENDP
IMPRIME PROC NEAR
; IMPRIME UMA MATRIZ M X N E ARMAZENA NA MEMORIA
; ENTRADA - BX O OFFSET DA MATRIZ, CH NUMERO DE LINHAS E DH NUMERO DE COLUNAS
; SAIDA - MATRIZ IMPRESSA
PUSH AX ; SALVAR OS REGISTRADORES NA PILHA
PUSH BX
PUSH CX
PUSH DX
PUSH SI
MOV AH,2
MOV DL,10
INT 21H
;MOV CH,3 ; # LINHA
;XOR BX,BX ; INDICE COLUNA
COLUNA: ; IMPRIME UMA COLUNA
MOV CL,DH ; # COLUNA
XOR SI,SI ; INDICE LINHA
LINHA: ; IMPIRME UMA LINHA
MOV DL,[BX][SI] ; LEIO ELEMENTO DA MATRIZ
OR DL, 30H ; NUMERO -> CARACTER
INT 21H ; IMPRIMO
MOV DL, ' '
INT 21H
INC SI ; PROXIMA COLUNA
DEC CL
JNZ LINHA
MOV DL, 10
INT 21H
ADD BX,3 ; PROXIMA LINHA
DEC CH
JNZ COLUNA
POP SI ; RESTAURO OS REGISTRADORES
POP DX
POP CX
POP BX
POP AX
RET
IMPRIME ENDP


inv PROC NEAR
; ZERA TODOS OS ELEMENTOS UMA MATRIZ M X N
; ENTRADA - BX O OFFSET DA MATRIZ, CH NUMERO DE LINHAS E DH NUMERO DE COLUNAS
; SAÍDA - TODOS OS ELEMSNTOS ZERADOS
PUSH AX ; SALVAR OS REGISTRADORES NA PILHA
PUSH BX
PUSH DX
PUSH CX
PUSH SI
;MOV CH,3 ; # LINHA
;XOR BX,BX ; INDICE COLUNA
COLUNAZ: ; IMPRIEM UMA COLUNA
MOV CL,DH ; # COLUNA
XOR SI,SI ; INDICE LINHA
LINHAZ: ; IMPIRME UMA LINHA
xchg si, bx
INC SI ; PROXIMA COLUNA
DEC CL
JNZ LINHAZ
ADD BX,3 ; PROXIMA LINHA
DEC CH
JNZ COLUNAZ
POP SI ; RESTAURO OS REGISTRADORES
POP DX
POP CX
POP BX
POP AX
RET
inv ENDP
END MAIN
